# Generated by Django 4.2.17 on 2026-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Demande en langage naturel')),
                ('query_type', models.CharField(choices=[('SQL', 'SQL (PostgreSQL/MySQL)'), ('MongoDB', 'MongoDB Query'), ('Django ORM', 'Django ORM')], default='SQL', max_length=20)),
                ('generated_code', models.TextField(verbose_name='Requête générée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
