# Generated by Django 4.2.17 on 2026-05-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du projet / BDD')),
                ('dialect', models.CharField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('MongoDB', 'MongoDB')], default='PostgreSQL', max_length=50)),
                ('schema_definition', models.TextField(help_text='Collez ici le DDL (CREATE TABLE...) ou la description des tables et types.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_utilisateur', models.TextField()),
                ('requete_generee', models.TextField(blank=True, null=True)),
                ('query_type', models.CharField(max_length=50)),
                ('execution_time', models.FloatField(blank=True, help_text="Temps de réponse de l'IA en secondes", null=True)),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Utile ?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.databaseschema')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GeneratedQuery',
        ),
    ]
