# Generated by Django 4.2.17 on 2026-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_databaseschema_queryhistory_delete_generatedquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseschema',
            name='dialect',
            field=models.CharField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('MongoDB', 'MongoDB'), ('Django ORM', 'Django ORM')], default='PostgreSQL', max_length=50),
        ),
    ]
