# Generated by Django 4.2.17 on 2026-05-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif pour retrouver cette session', max_length=200, verbose_name='Nom de session')),
                ('selected_models', models.TextField(blank=True, default='', help_text='Noms des modèles Django en scope, séparés par virgule', verbose_name='Modèles sélectionnés')),
                ('data_context', models.TextField(blank=True, default='[]', help_text='Résultats des requêtes exécutées (JSON)', verbose_name='Contexte de données')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de chat',
                'verbose_name_plural': 'Sessions de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterModelOptions(
            name='databaseschema',
            options={'verbose_name': 'Schéma / Projet', 'verbose_name_plural': 'Schémas / Projets'},
        ),
        migrations.AlterModelOptions(
            name='queryhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de requête', 'verbose_name_plural': 'Historique des requêtes'},
        ),
        migrations.AddField(
            model_name='databaseschema',
            name='models_filter',
            field=models.TextField(blank=True, default='', help_text='Noms des modèles à inclure (séparés par virgule). Vide = tous les modèles.', verbose_name='Filtrer les modèles'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text="Nom et prénom de l'auteur", max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Auteur principal du livre', on_delete=django.db.models.deletion.CASCADE, to='generator.author', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Titre complet du livre', max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='databaseschema',
            name='dialect',
            field=models.CharField(choices=[('PostgreSQL', 'PostgreSQL'), ('MySQL', 'MySQL'), ('SQLite', 'SQLite'), ('MongoDB', 'MongoDB'), ('Django ORM', 'Django ORM')], default='Django ORM', max_length=50),
        ),
        migrations.AlterField(
            model_name='databaseschema',
            name='schema_definition',
            field=models.TextField(blank=True, default='', help_text='Description optionnelle du projet / DDL.'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=20, verbose_name='Rôle')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='generator.chatsession')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
    ]
