# Generated by Django 4.2.17 on 2026-05-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Famille de produits (ex: Électronique, Mobilier, Textile)', max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, default='', help_text='Description commerciale de la catégorie', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du client particulier ou raison sociale de l'entreprise", max_length=200, verbose_name='Nom / Raison sociale')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('segment', models.CharField(choices=[('B2C', 'Particulier (B2C)'), ('PME', 'PME (B2B)'), ('GRAND', 'Grand compte'), ('PUBLIC', 'Secteur public')], default='B2C', help_text='Catégorie commerciale : B2C = particulier, PME = entreprise, GRAND = key account, PUBLIC = administration', max_length=10, verbose_name='Segment client')),
                ('chiffre_affaires_cumul', models.DecimalField(decimal_places=2, default=0, help_text="Chiffre d'affaires total généré depuis la création du compte", max_digits=12, verbose_name='CA cumulé (€)')),
                ('date_creation', models.DateField(verbose_name='Date de création du compte')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Identifiant unique (ex: CMD-2024-00042)', max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('date_livraison_prevue', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CONFIRMEE', 'Confirmée'), ('EXPEDIEE', 'Expédiée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', help_text='État actuel de la commande dans le cycle de vie', max_length=12, verbose_name='Statut')),
                ('mode_paiement', models.CharField(choices=[('CB', 'Carte bancaire'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces')], default='CB', max_length=10, verbose_name='Mode de paiement')),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, help_text='Remise commerciale appliquée sur le total de la commande (0–100)', max_digits=5, verbose_name='Remise globale (%)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='Vente.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Région administrative française (ex: Île-de-France, Auvergne-Rhône-Alpes)', max_length=100, unique=True, verbose_name='Région')),
                ('code', models.CharField(help_text='Code court utilisé en interne (ex: IDF, ARA)', max_length=10, unique=True, verbose_name='Code région')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de famille du commercial', max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(help_text='Prénom du commercial', max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email professionnel')),
                ('objectif_mensuel', models.DecimalField(decimal_places=2, help_text="Chiffre d'affaires HT mensuel cible du commercial", max_digits=10, verbose_name='Objectif mensuel (€)')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, help_text='False = commercial parti ou suspendu', verbose_name='Actif')),
                ('region', models.ForeignKey(blank=True, help_text='Zone géographique de prospection du commercial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='Vente.region', verbose_name='Région assignée')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateField(verbose_name='Date du retour')),
                ('motif', models.CharField(choices=[('DEFAUT', 'Produit défectueux'), ('ERREUR', 'Erreur de commande'), ('INSATISF', 'Insatisfaction client'), ('DOUBLON', 'Commande en doublon'), ('DELAI', 'Délai de livraison dépassé'), ('AUTRE', 'Autre')], help_text='Raison principale du retour client', max_length=10, verbose_name='Motif du retour')),
                ('montant_rembourse', models.DecimalField(decimal_places=2, help_text='Montant effectivement crédité au client', max_digits=10, verbose_name='Montant remboursé HT (€)')),
                ('traite', models.BooleanField(default=False, help_text='True = remboursement émis et validé', verbose_name='Traité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='Vente.commande', verbose_name="Commande d'origine")),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
                'ordering': ['-date_retour'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Code SKU interne (ex: ELEC-001)', max_length=20, unique=True, verbose_name='Référence produit')),
                ('nom', models.CharField(help_text='Désignation commerciale complète', max_length=200, verbose_name='Nom du produit')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix de vente hors taxes en euros', max_digits=10, verbose_name='Prix unitaire HT (€)')),
                ('cout_achat', models.DecimalField(decimal_places=2, help_text='Prix de revient pour calculer la marge brute', max_digits=10, verbose_name="Coût d'achat HT (€)")),
                ('stock', models.IntegerField(default=0, help_text="Nombre d'unités en stock au moment de la requête", verbose_name='Stock disponible')),
                ('actif', models.BooleanField(default=True, help_text='False = produit arrêté, ne plus proposer à la vente', verbose_name='Produit actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(help_text='Famille à laquelle appartient ce produit', on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='Vente.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'unités commandées", verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, help_text='Prix au moment de la commande, peut différer du tarif actuel', max_digits=10, verbose_name='Prix unitaire HT (€)')),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, help_text='Remise spécifique à cette ligne (0–100)', max_digits=5, verbose_name='Remise ligne (%)')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Vente.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='Vente.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='vendeur',
            field=models.ForeignKey(blank=True, help_text='Vendeur ayant saisi la commande ; null si vente en ligne directe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='Vente.vendeur', verbose_name='Commercial'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Région administrative du client — utile pour l'analyse géographique", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='Vente.region', verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='client',
            name='vendeur_attitré',
            field=models.ForeignKey(blank=True, help_text='Vendeur responsable de ce compte client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='Vente.vendeur', verbose_name='Commercial attitré'),
        ),
    ]
